version: "3.3"
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    networks:
      main:
        aliases:
          - mongodb
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
